sudo: required
services:
  - docker

before_install:
  - docker build -t ikholwadia/docker-aws-project -f Dockerfile.dev .

script:
  - docker run -e CI=true ikholwadia/docker-aws-project npm run test