sudo: required
services:
  - docker

before_install:
  - docker build -t ikholwadia/docker-aws-project -f Dockerfile.dev .

script:
  - docker run -e CI=true ikholwadia/docker-aws-project npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-AWS-project"
  env: "Dockerawsproject-env"
  bucket_name: "elasticbeanstalk-us-east-1-005515863523"
  bucket_path: "Docker-AWS-project"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  